"use client";

// Central icon indirection so nodes/panels can reference icons by name.
import {
  ArrowRight,
  ArrowsClockwise,
  ArrowsOutCardinal,
  ArrowsOutSimple,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChatText,
  Check,
  CircleNotch,
  Copy,
  CornersOut,
  Cube,
  Download,
  Eye,
  FilmSlate,
  Gear,
  GridFour,
  Hand,
  Image as ImageIcon,
  Lightning,
  MagicWand,
  Minus,
  MusicNotes,
  Paperclip,
  Pause,
  Play,
  Plus,
  Question,
  Scissors,
  Selection,
  Sparkle,
  SquaresFour,
  Stack,
  TextT,
  Trash,
  TShirt,
  UploadSimple,
  VideoCamera,
  Warning,
  X,
  ClockCounterClockwise,
  FolderOpen,
  PaintBrush,
  Palette,
  ShareNetwork,
  Swap,
} from "@phosphor-icons/react";
import type { ComponentType } from "react";

export interface IconProps {
  size?: number;
  weight?: "thin" | "light" | "regular" | "bold" | "fill" | "duotone";
  className?: string;
}

const REGISTRY: Record<string, ComponentType<IconProps>> = {
  ArrowRight,
  ArrowsClockwise,
  ArrowsOutCardinal,
  ArrowsOutSimple,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChatText,
  Check,
  CircleNotch,
  ClockCounterClockwise,
  Copy,
  CornersOut,
  Cube,
  Download,
  Eye,
  FilmSlate,
  FolderOpen,
  Gear,
  GridFour,
  Hand,
  Image: ImageIcon,
  Lightning,
  MagicWand,
  Minus,
  MusicNotes,
  PaintBrush,
  Palette,
  Paperclip,
  Pause,
  Play,
  Plus,
  Question,
  Scissors,
  Selection,
  ShareNetwork,
  Sparkle,
  SquaresFour,
  Stack,
  Swap,
  TextT,
  Trash,
  TShirt,
  UploadSimple,
  VideoCamera,
  Warning,
  X,
};

export function Icon({ name, ...props }: IconProps & { name: string }) {
  const C = REGISTRY[name] ?? Question;
  return <C {...props} />;
}
